name: Python Check

on: push

jobs:
  check-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install boto3
        run: pip install boto3

      - name: Check Python syntax
        run: python -m py_compile aws-exercises/01-boto3-basics/*.py
      
      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest testing-exercises/
